feat: add explicit paging to bigquery extractor
goto/meteor pull request #25
Opened 2023-07-25 04:42 UTC by spy16

2023-07-25 08:02 UTC, sudo-suhas requested changes

2023-07-25 08:02 UTC, sudo-suhas commented on plugins/extractors/bigquery/bigquery.go
> +		if errors.Is(err, iterator.Done) || nextToken == "" {
Don't think we need to check `iterator.Done` here. Also, we should have the `nextToken` check at the end of the loop. There might not be a next page but we could have gotten some results in the current page.

2023-07-25 08:02 UTC, sudo-suhas commented on plugins/extractors/bigquery/bigquery.go
> +		if errors.Is(err, iterator.Done) || nextToken == "" {
similar change needed for tables pager as well.

2023-07-26 04:12 UTC, sudo-suhas commented on plugins/extractors/bigquery/bigquery.go
> +	pageSize := pickFirstNonZero(e.config.DatasetPageSize, e.config.MaxPageSize, 1)
Lets use a larger default page size. Could be 10 for datasets and 50 for tables.

2023-07-26 07:27 UTC, sudo-suhas approved these changes

2023-07-26 11:45 UTC, haveiss approved these changes

2023-07-26 13:06 UTC, merged