feat: optimus support maxcompute
goto/meteor pull request #70
Opened 2024-10-30 12:15 UTC by luthfifahlevi

2024-10-31 06:26 UTC, haveiss commented on plugins/extractors/optimus/optimus.go
> +		resource, err := e.createResource(dependency.Dependency)
let's add unit test

2024-10-31 07:13 UTC, irainia requested changes

2024-10-31 07:13 UTC, irainia commented on plugins/extractors/optimus/optimus.go
> +func (e *Extractor) createResource(dependency string) (*v1beta2.Resource, error) {
we can shorten this method by using immediate return, like:

```go
switch {
  case A:
    return e.createMaxComputeResource(dependency)
  case B:
    return e.createBigQueryResource(dependency)
  default:
   return something
}
```

though, what is the expected `something` here? are we going to return error? because the current one returns nil and nil

2024-10-31 07:13 UTC, irainia commented on plugins/extractors/optimus/optimus.go
> +	case strings.HasPrefix(dependency, "maxcompute://"):
please move this to a constant, and if possible to a dedicated type

2024-10-31 07:13 UTC, irainia commented on plugins/extractors/optimus/optimus.go
> +		strings.TrimPrefix(dependency, "maxcompute://"),
why don't we just send the trimmed version? rather than checking things and then trimming, `maxcompute://` and `bigquery://` are written in two places

2024-10-31 07:13 UTC, irainia commented on plugins/util.go
> +func MaxComputeTableFQNToURN(fqn string) (string, error) {
can you put the FQN definition into this function? because it will also be visible from the outside

2024-10-31 07:13 UTC, irainia commented on plugins/util.go
> +	if len(ss) != 3 {
please add this in a constant, we don't want an increasing magic number

2024-10-31 07:13 UTC, irainia commented on plugins/util.go
> +				"unexpected MaxCompute table FQN '%s', each component should not blank", fqn,
suggestion message to be updated for:
```go
each component should not blank
```
 into
```go
each component should be neither blank nor whitespaces only
```

2024-10-31 08:31 UTC, luthfifahlevi commented on plugins/extractors/optimus/optimus.go
> +		strings.TrimPrefix(dependency, "maxcompute://"),
Actually should be trimmed from optimus. I changed my mind, I think no need trimming logic again in maxcompute, I'll adjust the logic 🆗

2024-11-06 06:48 UTC, luthfifahlevi commented on plugins/util.go
> +				"unexpected MaxCompute table FQN '%s', each component should not blank", fqn,
removed, related to this https://github.com/goto/meteor/pull/70#discussion_r1824071579

2024-11-11 04:15 UTC, irainia commented on plugins/extractors/optimus/optimus.go
> +func (e *Extractor) createResource(dependency string) (*v1beta2.Resource, error) {
I'm not sure why this is resolved, perhaps wrong click, un-resolving for now

2024-11-11 04:19 UTC, luthfifahlevi commented on plugins/extractors/optimus/optimus.go
> +func (e *Extractor) createResource(dependency string) (*v1beta2.Resource, error) {
oh sorry about that, I think I resolved all thread of spontaneity
btw it already handled mas in [here](https://github.com/goto/meteor/pull/70/files#diff-6835ac57a48503d1d6cbadfde8e8d50a99c22945a66a0a6cd19814ed296b7942R246-R253)

2024-11-14 04:28 UTC, irainia commented on plugins/extractors/optimus/optimus.go
> +func (e *Extractor) createResource(dependency string) (*v1beta2.Resource, error) {
the point being raised is, we can just remove this line:

```go
if err != nil {
    return nil, err
}
return resource, nil
```

please check if it's possible

2024-11-14 08:22 UTC, luthfifahlevi commented on plugins/extractors/optimus/optimus.go
> +func (e *Extractor) createResource(dependency string) (*v1beta2.Resource, error) {
oh I see, my bad. Updated mas @irainia , please re-review 🙏

2024-11-14 08:35 UTC, irainia approved these changes

2024-11-14 10:26 UTC, merged